name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        node-version-file: .nvmrc

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash

    - name: Install dependencies in example
      working-directory: ./example
      run: yarn install --immutable
      shell: bash
