name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Upgrade npm for trusted publishing
      run: npm install -g npm@latest
      shell: bash

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash

    - name: Install dependencies in example
      working-directory: ./example
      run: yarn install --immutable
      shell: bash
